---
stages:
  - build
  - test
  - deploy

phpspec:
  stage: build
  script:
    - /usr/local/bin/composer install
    - pwd
    - ls -la bin
    - bin/phpspec run --format pretty --no-interaction --no-code-generation
...
