---
stages:
  - build
  - test
  - deploy

phpspec:
  stage: build
  script:
    - /usr/local/bin/composer install
    - bin/phpspec run --format pretty --no-interaction --no-code-generation
  tags:
    - php
    - phpspec

phpunit:
  stage: build
  script:
    - /usr/local/bin/composer install
    - bin/phpspec run --format pretty --no-interaction --no-code-generation
  tags:
    - php
    - phpunit

...
