---
stages:
  - build
  - test
  - deploy

composer:install:
  stage: build
  script:
    - /usr/local/bin/composer install
  artifacts:
    paths:
      - vendor/
    expire_in: 2 days

php:phpspec:
  stage: test
  script:
    - bin/phpspec run --format pretty --no-interaction --no-code-generation
  dependencies:
    - composer:install
  tags:
    - php
    - phpspec

php:phpunit:
  stage: test
  script:
    - bin/phpunit
  dependencies:
    - composer:install
  tags:
    - php
    - phpunit

php:phpcs:
  stage: test
  script:
    - bin/phpcs src
  dependencies:
    - composer:install
  tags:
    - php

cucumber:
  stage: test
  script:
    - ruby --version
  dependencies:
    - composer:install
  tags:
    - ruby
    - cucumber
...
