---
stages:
  - build
  - test
  - deploy

before_script:
  - /usr/local/bin/composer install

phpspec:
  stage: build
  script:
    - bin/phpspec run --format pretty --no-interaction --no-code-generation
  tags:
    - php
    - phpspec

phpunit:
  stage: build
  script:
    - /usr/local/bin/composer install
    - bin/phpunit
  tags:
    - php
    - phpunit

phpcs:
  stage: build
  script:
    - bin/phpcs src
  tags:
    - php

cucumber:
  stage: build
  script:
    - ruby --version
  tags:
    - ruby
    - cucumber
...
