---
stages:
  - build
  - test
  - deploy

variables:
  COMPOSER_INSTALL: '--dev'

composer:install:
  stage: build
  script:
    - "/usr/local/bin/composer install ${COMPOSER_INSTALL}"
  artifacts:
    paths:
      - vendor/
    expire_in: 2 days

php:phpspec:
  stage: test
  script:
    - vendor/bin/phpspec run --format pretty --no-interaction --no-code-generation
  dependencies:
    - composer:install
  tags:
    - php
    - phpspec

php:phpunit:
  stage: test
  script:
    - vendor/bin/phpunit
  dependencies:
    - composer:install
  tags:
    - php
    - phpunit

php:phpcs:
  stage: test
  script:
    - vendor/bin/phpcs jard
  allow_failure: true
  dependencies:
    - composer:install
  tags:
    - php

cucumber:
  stage: deploy
  environment:
    name: staging
  only:
    - develop
  script:
    - ruby --version
  variables:
    COMPOSER_INSTALL: '--no-dev'
  dependencies:
    - composer:install
  tags:
    - ruby
    - cucumber
...
