---
- name: yum-clean-metadata
  command: yum clean all
  args:
    warn: no

- name: Install PHP packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ php_packages }}"
...
