---

- name: Set concurrent option
  lineinfile:
    dest: /etc/gitlab-runner/config.toml
    regexp: ^concurrent =
    line: concurrent = {{ gitlab_runner_concurrent }}
    state: present

- name: Set poll interval
  lineinfile:
    dest: /etc/gitlab-runner/config.toml
    regexp: ^check_interval =
    line: check_interval = {{ gitlab_runner_check_interval }}
    state: present
  when: "{{ gitlab_runner_check_interval }}"
  