---
- hosts: gitlab
  roles:
    - { role: gitlab }

- hosts: gitlab-ci
  roles:
    - { role : gitlab-ci }

- hosts: gitlab-runner
  vars:
    gitlab_runner_registration_token: "{{ hostvars['gitlab_controller']['gitlab_ci_registration_token']['stdout'] }}"
  roles:
    - { role: php }
    - { role: geerlingguy.composer }
    - { role : gitlab-runner }

- hosts: gitlab-runner-cucumber
  vars:
    rvm1_install_flags: '--auto-dotfiles'     # Remove --user-install from defaults
    rvm1_install_path:  /usr/local/rvm
    rvm1_user:          root
  roles:
    - { role: ruby }


# rt department: 020 7 230 0565
# 0207 230 7620
# ref JC/010000843/17/LB
...
