---
- hosts: gitlab
  roles:
    - { role: gitlab }

- hosts: gitlab-ci
  roles:
    - { role : gitlab-ci }


- hosts: gitlab-runner-cucumber
  roles:
    - { role: geerlingguy.ruby }

- hosts: gitlab-runner
  vars:
    gitlab_runner_registration_token: "{{ hostvars['gitlab_controller']['gitlab_ci_registration_token']['stdout'] }}"
    php_executable: '/opt/rh/rh-php56/root/usr/bin/php'
  roles:
    - { role : gitlab-runner }
    - { role: php }
    - { role: geerlingguy.composer }



...
