---
- hosts: gitlab
  roles:
    - { role: gitlab }

- hosts: gitlab-ci
  roles:
    - { role : gitlab-ci }

- hosts: gitlab-runner
  vars:
    gitlab_runner_registration_token: "{{ hostvars['gitlab_controller']['gitlab_ci_registration_token']['stdout'] }}"
  roles:
    - { role: php }
    - { role: geerlingguy.composer }
    - { role : gitlab-runner }

- hosts: gitlab-runner-cucumber
  vars:
    rbenv_owner: 'root'
    rbenv_group: 'root'
    rbenv:
      env: user
      version: v1.0.0
      default_ruby: 2.3.3
      rubies:
        - version: 2.3.3
    rbenv_users:
      - gitlab-runner
      - vagrant
  roles:
    - { role: ruby }
    - { role: zzet.rbenv }


# rt department: 020 7 230 0565
# 0207 230 7620
# ref JC/010000843/17/LB
...
